spring:
  application:
    name: alir-test-project
  datasource:
    url: jdbc:postgresql://localhost:5432/altir_test_project
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
flyway:
  url: jdbc:postgresql://localhost:5432/altir_test_project
  schemas: altir_test_project
  user: "postgres"
  password: "postgres"
