version: "2.3"

services:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: altir_test_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres: